# name: Run E2E Tests

# on: [pull_request]

# jobs:
#   run-e2e-tests:
#     name: Run E2E Tests
#     runs-on: ubuntu-latest

#     services:
#       rocket-solid-pg:
#         image: bitnami/postgresql
#         ports:
#           - 5432:5432
#         environment:
#           - POSTGRESQL_USERNAME=docker
#           - POSTGRESQL_PASSWORD=docker
#           - POSTGRESQL_DATABASE=apisolid

#     steps:
#       - uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: 22
#           cache: "npm"

#       - run: npm ci

#       - run: npm run test:e2e
#         env:
#           JWT_SECRET: testing
#           DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"

name: Run E2E Tests

on: [push]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      rocket-solid-pg:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid
        options: >-
          --health-cmd="pg_isready -U docker -d apisolid"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate --schema=prisma/schema.prisma
        env:
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"

      - name: Apply migrations
        run: npx prisma migrate deploy --schema=prisma/schema.prisma
        env:
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
